GET http://localhost:13377/profile/1

###
GET http://localhost:13377/

###

POST http://localhost:13377/signup
Content-Type: application/json

{
    "username": "Kyle",
    "password": "donut"
}

###

POST http://localhost:13377/login
Content-Type: application/json

{
    "username": "Kyle",
    "password": "donut"
}

###

GET http://localhost:13377/auth?ID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX0lEIjoxLCJpYXQiOjE1OTM1NDIwMzMsImV4cCI6MTU5MzU0MjIxM30.ZG75AP8S7Q9KEzmUZQ5EfUSR7zHJwP3m52C-xZC0njs
